## 2、感知机学习算法

主要是求解损失函数的最小值：
$$\min \limits_{w,b} L(w,b)=-\sum_{x_i\in M}y_i(w\centerdot x_i +b)$$
其中M属于误分类点的集合。

下面是算法的实现：

In [40]:

from numpy import *
import sys
def loadset():
    data = array([[3,3,1],[4,3,1],[1,1,-1]])
    return data

def perceptron(dataset):
    '''
        @brief:感知机算法主实现
    '''
    n = len(dataset)
    w = zeros((1,n-1));b = 0;a = 1
    end_status = False
    while end_status == False:
        for record in dataset:
            end_status = True
            yi = record[-1:]
            mat_re = mat(record[:-1])
            tmp_result = yi*(w*mat_re.T + b)
            if tmp_result <= 0:
                w = w + a * yi * mat_re
                b = b + a * yi
                end_status = False
                print(w,b)
    return w,b
        
        
    
    
def main():
    data = loadset()
    print(perceptron(data))
    
if __name__ == "__main__":
    main()

[[3. 3.]] [1]
[[2. 2.]] [0]
[[1. 1.]] [-1]
[[0. 0.]] [-2]
[[3. 3.]] [-1]
[[2. 2.]] [-2]
[[1. 1.]] [-3]
(matrix([[1., 1.]]), array([-3]))
